version: '3'

services:
  db-mysql-dev:
    image: mysql:8.0
    container_name: mysql_container_dev
    restart: always
    environment:
      MYSQL_DATABASE: questportal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: 4454
    ports:
      - "3306:3306"
    volumes:
      - ./db_data_dev:/var/lib/mysql

  question_portal:
    image: 'question-portal-dev-image'
    container_name: 'question-portal-dev'
    ports:
      - 8082:8080
    environment:
      - 'DB_URL=jdbc:mysql://db-mysql-dev:3306/questportal?allowPublicKeyRetrieval=true&useSSL=false'
      - 'DB_USERNAME=user'
      - 'DB_PASSWORD=password'
    volumes:
      - ./Upload_dev:/Upload